[world]
name = "Tournament"
description = "Tournament component used to create and compete in tournaments across Dojo games."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "tournaments"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "budokan"

[env]
chain_id = "KATANA_LOCAL"
rpc_url = "http://localhost:5050/"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = "0x02f808e319783173b7a36bae6ab318fb98f6553fce73786b430cc02110483fd4"  # Uncomment and update this line with your world address.

[writers]
# Tournament
"budokan-Tournament" = ["budokan-tournament_mock"]
"budokan-Registration" = ["budokan-tournament_mock"]
"budokan-Leaderboard" = ["budokan-tournament_mock"]
"budokan-PlatformMetrics" = ["budokan-tournament_mock"]
"budokan-TournamentTokenMetrics" = ["budokan-tournament_mock"]
"budokan-PrizeMetrics" = ["budokan-tournament_mock"]
"budokan-EntryCount" = ["budokan-tournament_mock"]
"budokan-Prize" = ["budokan-tournament_mock"]
"budokan-Token" = ["budokan-tournament_mock"]
"budokan-TournamentConfig" = ["budokan-tournament_mock"]
"budokan-PrizeClaim" = ["budokan-tournament_mock"]
# Game
"budokan-GameMetadata" = ["budokan-game_mock"]
"budokan-GameCounter" = ["budokan-game_mock"]
"budokan-SettingsDetails" = ["budokan-game_mock"]
"budokan-SettingsCounter" = ["budokan-game_mock"]
"budokan-Settings" = ["budokan-game_mock"]
"budokan-TokenMetadata" = ["budokan-game_mock"]
"budokan-Score" = ["budokan-game_mock"]


[migration]
order_inits = []
skip_contracts = ["budokan-Budokan"]
