# Realms World
world_address = "0x06a9e4c6f0799160ea8ddc43ff982a5f83d7f633e9732ce42701de1288ff705f"
rpc = "https://api.cartridge.gg/x/starknet/mainnet"

[indexing]
index_pending = true
world_block = 1198152 # dark shuffle deployment block
contracts = [
  "ERC721:0x020fc3c9efd0dde5f53642dac7f53638aeaae98ff9af5f1642546f389ce9dec5", # dark shuffle
]

[events]
raw = true